comment:
  layout: "condensed_header, diff, flags, components"
  
component_management:
  individual_components:
    - component_id: backend
      name: backend test
      paths:
        - ./app/backend
